- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.json
> Update to 3.0.1

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.json
> Update to 3.0.2

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.json
> Update to 3.0.3

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
> Update SCons to 4.0.1

- org.godotengine.Godot.appdata.xml
> Update AppStream metadata to mention Flatpak caveats

- org.godotengine.Godot.yaml
`master` version of https://github.com/flathub/org.godotengine.Godot/pull/90.
> Update Godot to 3.4

- org.godotengine.Godot.yaml
This closes https://github.com/flathub/org.godotengine.Godot/issues/104.
> Update Godot to 3.5

- README.md
> Make Blender instructions more like guidelines

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Using TuxFamily download link this time around
> Update Godot to 4.2 Beta 5 for Flathub Beta

- org.godotengine.Godot.appdata.xml
Let me know if this notice is good so it can be added to https://github.com/flathub/org.godotengine.GodotSharp and https://github.com/flathub/org.godotengine.Godot3 as well.
- This closes https://github.com/flathub/org.godotengine.Godot/issues/141.
> Mark this Flatpak as unofficial

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
> Update Godot to 4.2.1

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
> Update Godot to 4.3-dev5 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
> Create libspeechd module for text-to-speech support

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Sorry for the delay in getting this out there.
> Update Godot to 4.4-dev1 for Flathub Beta

- org.godotengine.Godot.yaml
Also update shared-modules reference to latest commit
> Update to fdo 24.08

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Apologies for the long delay in getting this one out here. I got rather busy.
> Update Godot to 4.4-dev3 for Flathub Beta

- README.md
Probably not worth republishing the whole app for, but correct.
> README: update local build instructions

- .gitmodules
- org.godotengine.Godot.yaml
See:
- https://github.com/flathub/org.godotengine.godot.BaseApp/issues/47
- https://github.com/godotengine/godot/issues/3787
> Remove unneeded glu dependency

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
> Update to 4.5-beta7

- org.godotengine.Godot.appdata.xml
- Non-C# counterpart of https://github.com/flathub/org.godotengine.GodotSharp/pull/30.
- See https://github.com/flathub/org.godotengine.GodotSharp/issues/29.
> Tweak unofficial note in AppStream metadata for better display on Flathub
