flathub/org.godotengine.Godot

- org.godotengine.Godot.json
This updates SCons to the latest version. (By the way, as of 3.0, it is compatible with both Python 3 and Python 2.)
> Update SCons to version 3.0.1

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.json
This updates to the latest upstream version. Note that this does not include AppStream file updates as they were not merged in time for 3.0.6. However, they should be available for 3.0.7.
> Update to 3.0.6

- org.godotengine.Godot.yaml
This also switches to GCC as compiler, as Godot's build system only supports enabling LTO with GCC.
> Build with link-time optimization enabled for better performance

- org.godotengine.Godot.yaml
This makes the Flatpak smaller and build faster. A base application is in the works, so that projects using Godot can be easily packaged as Flatpaks.
> Remove unused release template

- org.godotengine.Godot.yaml
Python 2 was removed from the runtime, so the manifest was updated to use Python 3.
> Update Freedesktop runtime to 19.08

- org.godotengine.Godot.appdata.xml
This closes #48.
We should move to the [upstream-provided metadata](https://github.com/godotengine/godot/blob/master/misc/dist/linux/org.godotengine.Godot.appdata.xml) in the future, but it needs further tweaks before it can be used out of the box.
> Fix the version being outdated in the AppStream metadata

- android-export-defaults.patch
- org.godotengine.Godot.yaml
This enables spawning host processes via flatpak-spawn by creating wrapper scripts in /app/bin and changes the default editor preference paths to the correct values.
Both utilities must be installed on the host and be accessible via PATH environment variable.
Closes flathub/org.godotengine.Godot#15
Closes godotengine/godot-website#60
http://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn
> Add wrapper scripts for adb and jarsigner

- org.godotengine.Godot.yaml
This makes it easier to copy-paste script lines between Flatpak manifests.
> Use the `$FLATPAK_ID` environment variable to make code reuse easier

- README.md
Closes #55
See also godotengine/godot#39267
> Document running an external editor outside of the sandbox

- org.godotengine.Godot.yaml
This closes https://github.com/flathub/org.godotengine.Godot/issues/83.
> Update to FreeDesktop 21.08 runtime

- org.godotengine.Godot.yaml
`beta` version of #89. This ensures the `beta` branch doesn't fall behind the stable branch.
> Update Godot to 3.4

- org.godotengine.Godot.yaml
Editor version of https://github.com/flathub/org.godotengine.godot.BaseApp/pull/18.
This was due to an upstream packaging issue of the source tarball which is now fixed.
For the record, official Godot editor binaries were not affected by this bug.
> Fix 3.4.1 reporting itself as `rc` instead of `stable`

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
`beta` version of https://github.com/flathub/org.godotengine.Godot/pull/94.
> Update Godot to 3.4.2

- org.godotengine.Godot.yaml
This makes Godot request the dedicated GPU when available to improve performance.
> Keep PrefersNonDefaultGPU in the `.desktop` file

- org.godotengine.Godot.yaml
Same as #110 but installs SCons using `pip install .` instead of `setup.py install`. Note that `--no-index` prevents pip from downloading packages from the internet, so this is still fully offline.
Using pip solves the `PackageNotFoundError` in #110
> Bump runtime to 22.08

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
I just thought I'd quickly fork the Flatpak repo and replace the source file link and SHA256 for the Godot source code in the YAML file. It isn't much at the moment, but I'd like to help somehow.
It's my first time working with Flatpaks to build software like this, so I hope I didn't botch it.
> Update Godot to 4.0

- README.md
While working on the proposal to select the Blender executable directly, I realized that since flatpak-spawn already runs, we can create a script that can run blender on the host. From my limited testing, it seems to work.
> Update README to include Blender information

- README.md
This matches the Flatpak manifest.
> Update FreeDesktop SDK version to install for building in README

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
- Update release version on `org.godotengine.Godot.appdata.xml`.
- Update sha256 and source url to match the 4.0.1 release.
> Update Godot to 4.0.1

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Using GitHub link to source download this time as it hasn't been uploaded to TuxFamily yet (I've no idea why). We can use the TuxFamily source download when it becomes available (or when the next Godot version is uploaded there).
> Update Godot to 4.1.1

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
In [appdata.xml](https://github.com/Zishan-Rahman/org.godotengine.Godot/blob/693db5a9c326d4b796b564de4a2f9b11666132d7/org.godotengine.Godot.appdata.xml#L49), I used the TuxFamily publish date for 4.2-dev6's release date, because it was released a day before [the blog article on it](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-6/) got published.
> Update Godot to 4.2-dev6 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Since it looks like Godot releases will still be hosted on TuxFamily, as well as GitHub, I'm using the TuxFamily link for the Godot source file here (and for future releases too).
> Update Godot to 4.1.2

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Should take the place of #136 now that [Godot 4.2 Beta 2](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-2/) was just released.
> Update Godot to 4.2-beta2 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Using GitHub releases download link this time around
> Update Godot to 4.2-beta4 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
The commits in #135 have been used here, by basing _this_ PR's branch on #135's branch, so I'm closing #135 in favour of this.
I used the TuxFamily upload link here. While [the accompanying blog post](https://godotengine.org/blog/) was published on November _2<sup>nd</sup>_, [the Godot 4.1.3 files (for the stable release)](https://downloads.tuxfamily.org/godotengine/4.1.3/) were uploaded to TuxFamily on November _1<sup>st</sup>_, so I used November 1<sup>st</sup> as the release date instead of November 2<sup>nd</sup>.
I apologise for being a bit late to updating the Godot Flatpak this time.
> Update Godot to 4.1.3 (and update appdata.xml with links and other things)

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Using TuxFamily download link.
The blog post was published 1 day prior to the files getting uploaded to TuxFamily (they were presumably already uploaded to https://godotengine.org/download/archive/4.2-rc2/ on that day), hence that date being used instead of the 25th November 2023 date shown on the TuxFamily page.
> Update Godot to 4.2 RC 2 for Flathub Beta

- org.godotengine.Godot.yaml
- Setting runtime to `org.freedesktop.Sdk`, sandboxed Godot will be able to access SDK extensions through `/usr/lib/sdk`, without bundling JRE at build time.
- Set JAVA_HOME to use OpenJDK 17 for default , as stated in official Godot documentation.
> Use Freedesktop SDK as runtime

- org.godotengine.Godot.yaml
When exporting to Android, package signing will fail if Java executables is not in `PATH`, even when `JAVA_HOME` is set. Exporting with `Use Gradle Build` enabled seems not affected by this.
This PR simply source the `enable.sh` provided by OpenJDK SDK extension that will append `$JAVA_HOME/bin` to `PATH` before running Godot editor. By locating the path based on `JAVA_HOME`, users can override the path if different OpenJDK version is installed.
> Append java executables to PATH based on JAVA_HOME

- org.godotengine.Godot.yaml
#151 and #152 broke the build pipeline for Android by completely removing the Java Sdk Extension from the manifest and therefore Java from the build.
It was instead replaced by an environment variable JAVA_HOME pointing to a now non-existing directory ("/usr/lib/sdk/openjdk17", which is only accessible at build time or when running the flatpak with devel permissions), which caused the apksigner-step to fail with the message:
>  editor/export/editor_export_platform.h:179 - Code Signing: All 'apksigner' tools located in Android SDK 'build-tools' directory failed to execute. Please check that you have the correct version installed for your target sdk version. The resulting APK is unsigned.
See also godotengine/godot-docs#8742
This patch reverts to the old behaviour of installing the …
> Use Java from the official Freedesktop Sdk Extension

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
The reason why #155 stemmed from the need to revert changes made in #151 and #152 is because, while Java is available during build time, it _isn't_ always available afterwards to the end user, who might not have `org.freedesktop.Sdk.Extension.openjdk17` installed separately. This PR addresses that by making sure the OpenJDK 17 Flatpak gets installed _with_ the Godot Flatpak, and that the Godot Flatpak can access it. 
_May_ fix #157 as the OpenJDK 17 Flatpak includes Gradle binaries.
> Configure Godot Flatpak so that OpenJDK 17 extension installs separately along with it

- org.godotengine.Godot.yaml
When I tried to install the test build for #158, it seemed that the OpenJDK 17 SDK extension didn't install with it. In fact, I can't find a JDK in there at all.
Upon finding out #158 had just been merged before I got to fixing it, I thought I'd try to fix it with _this_ PR, otherwise Android builds will be basically non-existent. Please do not merge this PR until we're _absolutely_ sure Android exports can be built with it. I'm going to test it myself each time the test build succeeds, and I highly encourage others who want to test each coming test build to do the same.
> Try to fix SDK extension installation with Godot Flatpak

- org.godotengine.Godot.yaml
After #160, installing `org.godotengine.Godot` from Flathub will have `org.freedesktop.Sdk.Extension.openjdk17` installed together so that flatpak godot do not need to bundle JDK itself. This PR does the clean up of unused steps since #151 from manifest including:
- unused `add-ld-path` (no need to add lib path to `LD_LIBRARY_PATH` as jdk executables have rpath to `../lib`)
- unused symlink `/app/jre` (it is not used by wrapper script anymore)
- unused override-able `JAVA_HOME` variable as we have already configured JDK path to located at `/app/jdk`
> JDK extension setup cleanup after #160

- .github/workflows/update.yaml
- org.godotengine.Godot.yaml
Fixes #163.
I have also added a GitHub Actions configuration file on this PR, but it may not get automatically set up once this PR get merged. If GitHub Actions doesn't get set up once this PR gets merged, it could be that we have to get it set up manually or remove the preset configuration entirely (note that several repositories [such as this one](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk21) have the external data checker running on them _without_ a GitHub Actions workflow).
> Add Flatpak External Data Checker configuration for Godot and SCons

- org.godotengine.Godot.yaml
Godot 4.3 adds opt-in Wayland support. To use this, the Wayland socket
is of course needed.
--socket=x11 is left as-is rather than being replaced with fallback-x11
because X11 remains the default; manual intervention is needed to
configure the editor and/or game to use Wayland.
> Beta: Allow access to Wayland socket

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Return to using TuxFamily download links for Godot sources as TuxFamily is now back up.
> Update Godot to 4.3-beta2 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Also remove default-branch setting from Flatpak manifest to fix "toplevel-unnecessary-branch" validation error
Closes #177
> Update Godot to 4.3 RC 3 for Flathub Beta

- org.godotengine.Godot.yaml
Godot 4.3 adds opt-in Wayland support. To use this, the Wayland socket
is of course needed.
--socket=x11 is left as-is rather than being replaced with fallback-x11
because X11 remains the default; manual intervention is needed to
configure the editor and/or game to use Wayland.
(cherry picked from commit 673564087d94ab47611628d731cf55f617b6406d)
> Allow access to Wayland socket

- org.godotengine.Godot.yaml
Partially addresses #183
It doesn't fix the `No such file or directory: '/github/workspace/shared-modules/glu/glu-9.json'` warning (though _that_ module has no `x-checker-data` set yet), but this should _at least_ fix the checking error for Godot's source code. [The old project ID doesn't work anymore for some reason, as its Anitya page now shows a 404 error.](https://release-monitoring.org/project/12162/)
> Use new Anitya project ID for Godot sources

- org.godotengine.Godot.yaml
Addresses Flatpak External Data checker errors in #183, specifically [here](https://github.com/flathub/org.godotengine.Godot/issues/183#issuecomment-2308984808), originally written by @Calinou (sorry for the ping):
> I still get this notification every hour as of [9c77d1f](https://github.com/flathub/org.godotengine.Godot/commit/9c77d1f609f994b98e12f92ae8327fff16aba1ca):
> 
> ```
> Run docker://ghcr.io/flathub/flatpak-external-data-checker:latest
> /usr/bin/docker run --name ghcrioflathubflatpakexternaldatacheckerlatest_ee5493 --label 12b425 --workdir /github/workspace --rm -e "GIT_AUTHOR_NAME" -e "GIT_COMMITTER_NAME" -e "GIT_AUTHOR_EMAIL" -e "GIT_COMMITTER_EMAIL" -e "EMAIL" -e "GITHUB_TOKEN" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" …
```
> Fix typos in Flatpak External Data Checker URL template

- org.godotengine.Godot.yaml
- Godot counterpart of https://github.com/flathub/org.godotengine.GodotSharp/pull/19.
These options are not present anywhere in 4.3's source code.
> Remove unused SCons options

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Using GitHub downloads link this time as files for 4.4-dev4 haven't been uploaded to TuxFamily yet (at the time this PR has been opened).
> Update Godot to 4.4-dev4 for Flathub Beta

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Also incorporate @MateusRodCosta's Freedesktop runtime upgrade from #191 (sorry for the ping).
> Update Godot to 4.4-dev5 for Flathub Beta

- .github/workflows/update.yaml
- README.md
- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
Although this looks big, it's just a merge of `master` (which fixes  #196), plus #197, and then an update to the latest dev release, so only the last 3 patches are new.
```
$ git log --graph --decorate --pretty=oneline --abbrev-commit master~.. beta~..
* 86f6c0e (HEAD -> update-to-4.4-dev6, origin/update-to-4.4-dev6) Update to Godot 4.4-dev6
*   f80ae5c Merge with stable branch
|\  
| * 87595c9 (origin/update-README, update-README) README: update local build instructions
| * 4d6f763 (upstream/master, upstream/HEAD, master) Update to fdo 24.08 (#191)
* e2ead0d (upstream/beta, beta) Update Godot to 4.4-dev5 for Flathub Beta (#194)
```
Diff to master:
```
diff --git a/README.md b/README.md
index 4fc7c94..4fb5b14 100644
--- a/README.md
+++ b/README.md
@@ -84,5 +84,5 @@ then enter the …
```
> Update to 4.4-dev6

- .gitmodules
- org.godotengine.Godot.yaml
This also cherry-picks the change from #199, resynchronizing the stable and beta branches.
> Update to 4.4 dev7

- org.godotengine.Godot.appdata.xml
- org.godotengine.Godot.yaml
I can barely keep up! Maybe some automation is in order. But betas & release candidates don't seem to get tagged in https://github.com/godotengine/godot/releases / https://github.com/godotengine/godot/tags .
> Update to 4.4~rc3

- org.godotengine.Godot.yaml
Since godotengine/godot#100052 is merged in v4.4, we can now configure linux dependency modules independently.
Currently Godot has a bug (godotengine/godot#91401) that if the engine is using system-provided harfbuzz library, it will crash when GDExtension libraries call `std::call_once` during static initialization. Libraries with such pattern are including but not limited to Tensorflow/Protobuf-based projects, GDExtension libraries with these dependencies will always crash flatpak Godot unless builtin harfbuzz is used.
This PR remove the `builtin_harfbuzz=no` from Scons flags, making the editor to use builtin harfbuzz instead of system-provided one from Freedesktop SDK/Platform. The editor executable size increase in my testing is from `139.2 MiB (145,966,624)` to `139.9 MiB …
> Use builtin harfbuzz to workaround GDExtension crash

- org.godotengine.Godot.appdata.xml
This adds some complementary [brand colors](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#good-brand-colors) e.g. for Flathub and GNOME Software. Preview, as provided by the [Flathub banner previewer](https://docs.flathub.org/banner-preview/):
> MetaInfo: Add brand colors
